image: docker:24.0.7

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_REGISTRY: "${CI_REGISTRY}"
  DOCKER_IMAGE: "${CI_REGISTRY_IMAGE}"

services:
  - docker:24.0.7-dind

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA
  only:
    - main  # Only run on main branch